import { text,type Locale } from "./site-config";
export type Section = {title:string;paragraphs:string[];prompt?:string;checklist?:string[]};
export type PostCopy = {title:string;excerpt:string;category:string;sections:Section[]};
export type Post = {slug:string;programId:string;number:string;kind:"example"|"experience";status:"planned"|"using"|"improving"|"stopped";completed:boolean;preview:"tasks"|"habits"|"timer";updatedAt:string;verifiedAt?:string;publicUrl?:string;tools:string[];ko:PostCopy;en:PostCopy};
export const posts:Post[]=[
{slug:"just-today",programId:"just-today",number:"01",kind:"example",status:"planned",completed:false,preview:"tasks",updatedAt:"2026-10-02",tools:[],
ko:{title:"할 일을 자꾸 잊는다면, 오늘 할 일만 보여주는 도구",excerpt:"길어진 목록 대신 오늘 필요한 몇 가지만. 기억을 돕는 작은 도구의 첫 요구 사항을 정리해 봅니다.",category:"생활 관리",sections:[
{title:"불편 · 목록은 길고, 오늘 할 일은 묻힌다",paragraphs:["일정 앱에는 이번 달에 할 일부터 언젠가 하고 싶은 일까지 함께 들어갑니다. 오늘 꼭 해야 할 일을 찾으려다 목록 전체를 다시 읽게 되는 상황을 가정해 봅니다.","이 글은 실제 사용 후기가 아닌 기획 예시입니다. 첫 도구를 어떻게 작게 정의하고, 무엇을 확인할지 살펴보기 위한 출발점입니다."]},
{title:"요구 · 오늘 필요한 것만 남기기",paragraphs:["첫 화면에는 오늘 할 일만 보여줍니다. 할 일을 추가하고, 완료 표시를 하고, 잘못 입력한 항목을 삭제하는 세 가지 행동부터 시작합니다.","달력, 우선순위 점수, 알림, 계정 가입은 첫 버전에서 제외합니다. 기능을 덜어낼수록 직접 확인해야 할 범위도 작아집니다."]},
{title:"제작 · AI에게 건넬 첫 요청",paragraphs:["요청에는 누가 쓸지, 무엇을 할지, 어디까지 만들지, 어떤 결과를 확인할지를 담습니다. 아래는 아직 실행하지 않은 요청문 예시입니다."],prompt:"나 혼자 사용할 ‘오늘 할 일’ 웹 도구를 만들고 싶습니다.\n\n기본 기능:\n1. 할 일의 내용을 입력하고 추가하기\n2. 오늘 할 일만 표시하기\n3. 완료 표시와 항목 삭제하기\n4. 새로고침해도 같은 브라우저에 내용이 남도록 하기\n\n빈 입력은 추가하지 말고, 긴 내용은 모바일 화면에서 줄바꿈해 주세요. 계정, 알림, 달력은 필요 없습니다. 브라우저 저장소의 한계도 설명해 주세요."},
{title:"확인 · 버튼이 눌린다고 끝은 아니다",paragraphs:["제작 후에는 평소에 일어날 만한 행동으로 확인합니다. 화면이 보이는 것과 정보가 유지되는 것은 서로 다른 문제입니다."],checklist:["빈 내용이나 공백만 입력해도 항목이 생기지 않는가?","완료와 삭제가 내가 선택한 항목에만 적용되는가?","새로고침 후 내용이 유지되는가?","날짜가 바뀌었을 때 지난 항목이 사라지거나 숨는 규칙이 명확한가?","좁은 화면에서 긴 할 일과 버튼이 겹치지 않는가?"]},
{title:"사용 · 실제로 관찰할 것",paragraphs:["실제 사용 기록은 아직 없습니다. 사용하게 되면 ‘목록을 보려고 열었는가’, ‘다른 메모와 중복으로 입력했는가’, ‘완료 표시 후 다시 찾을 필요가 있었는가’를 적어둘 계획입니다.","도구를 만드는 시간보다, 생활에서 다시 열어보게 되는지가 중요합니다. 사용 횟수나 절약한 시간은 측정한 뒤에만 기록합니다."]},
{title:"개선 · 필요가 생긴 뒤에 바꾸기",paragraphs:["지난 일을 남길지, 완료한 항목을 접을지, 입력을 더 빠르게 할지는 사용 중 확인한 불편을 보고 정합니다. 처음부터 모든 경우를 해결하려고 기능을 늘리지 않습니다.","브라우저 저장소는 기기를 바꾸면 이어지지 않고, 브라우저 데이터를 지우면 사라질 수 있습니다. 중요한 정보를 넣기 전에 내보내기가 필요한지도 판단해야 합니다."]},
{title:"현재 상태 · 제작 전 기획 예시",paragraphs:["이 도구는 아직 제작하거나 배포하지 않았습니다. 화면은 설명을 위한 구성 예시이며, 20개 제작 목표에 포함하지 않습니다.","첫 실행은 내가 요즘 실제로 잊는 할 일을 적고, 기존 도구로 해결되지 않는 이유를 한 문장으로 정리하는 것입니다."]}
]},
en:{title:"A small tool for just today’s tasks",excerpt:"A few things for today, instead of an endless list. Defining the first requirements for a little tool that helps you remember.",category:"Everyday life",sections:[
{title:"Problem · Today gets buried in a long list",paragraphs:["Imagine a task app that mixes this month’s plans with things you might do someday. To find what matters today, you end up reading the entire list again.","This is a planning example, not a firsthand review. It shows how to define a small first tool and decide what to check."]},
{title:"Requirements · Keep only what matters today",paragraphs:["The first screen should show only today’s tasks. Start with three actions: add a task, mark it complete, and delete a mistaken entry.","Leave calendars, priority scores, notifications, and accounts out of the first version. Fewer features also mean a smaller set of behaviors to verify."]},
{title:"Build · The first request to AI",paragraphs:["Describe who will use it, what it should do, what is out of scope, and what you expect to verify. This sample prompt has not been run."],prompt:"Build a personal web tool for today’s tasks.\n\nCore functions:\n1. Enter and add a task\n2. Show only today’s tasks\n3. Mark a task complete or delete it\n4. Keep tasks in the same browser after a refresh\n\nReject empty entries. Wrap long text on mobile. No accounts, notifications, or calendar. Explain the limitations of browser storage."},
{title:"Verify · A working button is just the start",paragraphs:["Once built, test actions that could happen in daily use. A visible screen and reliably stored information are separate concerns."],checklist:["Does it reject empty or whitespace-only entries?","Do completion and deletion affect only the selected task?","Do tasks survive a refresh?","Is the rule for yesterday’s tasks clear when the date changes?","Do long tasks and controls remain readable on narrow screens?"]},
{title:"Use · What to observe in real life",paragraphs:["There is no real usage record yet. When using it, note whether you open it to check tasks, duplicate information elsewhere, or need to find completed entries again.","Whether you return to the tool matters more than how quickly it was built. Record usage counts or time saved only after measuring them."]},
{title:"Improve · Change things after a need appears",paragraphs:["Decide whether to preserve old tasks, collapse completed ones, or speed up entry based on problems discovered during use. Avoid adding features for every imagined scenario.","Browser storage does not follow you to another device and can disappear when browser data is cleared. Consider export before storing important information."]},
{title:"Current status · A planning example",paragraphs:["This tool has not been built or released. Its screen is a conceptual layout and does not count toward the goal of 20 completed tools.","Start by listing tasks you actually forget and explain in one sentence why your existing tools are not helping."]}
]}},
{slug:"welcome-back-habits",programId:"welcome-back-habits",number:"02",kind:"example",status:"planned",completed:false,preview:"habits",updatedAt:"2026-10-02",tools:[],
ko:{title:"하루 빠져도 괜찮은, 다시 시작하는 습관 기록표",excerpt:"연속 기록보다 돌아온 날에 주목합니다. 놓친 하루 때문에 멈추지 않도록, 기록의 기준부터 바꾸는 실험입니다.",category:"기록과 회고",sections:[
{title:"불편 · 하루 빠지면 처음부터인가?",paragraphs:["연속 며칠이라는 숫자는 동기가 되기도 하지만, 기록이 끊겼을 때 부담이 될 수도 있습니다. ‘하루를 놓친 뒤 아예 기록을 멈추는 상황’을 해결할 수 있을지 생각해 봅니다.","이 글은 실제로 제작하거나 사용한 기록이 아닌 가상의 기획 예시입니다. 어떤 효과가 있는지는 사용 후 확인해야 합니다."]},
{title:"요구 · 잘한 날만 담담하게 남기기",paragraphs:["습관 하나를 정하고, 그 일을 한 날을 달력에 표시합니다. 연속 기록 순위나 실패 알림은 두지 않습니다. 빠진 날 다음에도 같은 버튼으로 다시 기록할 수 있어야 합니다.","체크를 잘못한 경우에는 취소할 수 있어야 합니다. 한 화면에서 이번 달 기록을 읽을 수 있으면 첫 버전에는 충분합니다."]},
{title:"제작 · 기록의 기준까지 설명하기",paragraphs:["‘습관 앱을 만들어 줘’보다 기록하고 싶은 태도를 함께 설명합니다. 다음 요청문은 아직 사용하지 않은 예시입니다."],prompt:"다시 시작하기 쉬운 개인 습관 기록표를 만들어 주세요.\n\n습관은 하나만 등록합니다. 이번 달 달력에서 실천한 날을 누르면 표시되고, 다시 누르면 취소됩니다. 연속 일수, 순위, 실패 메시지는 넣지 마세요. 날짜를 놓쳐도 다시 기록할 수 있어야 합니다.\n\n새로고침 후에도 같은 브라우저에서 기록이 유지되어야 합니다. 지난달 기록과 미래 날짜의 처리 방식은 먼저 설명해 주세요."},
{title:"확인 · 날짜와 취소 동작 점검하기",paragraphs:["날짜를 다루는 도구는 월이 바뀌는 날이나 다른 시간대에서 예상과 다르게 작동할 수 있습니다. 표시된 달력과 저장된 날짜를 함께 확인합니다."],checklist:["같은 날짜를 두 번 누르면 표시가 취소되는가?","월이 바뀌어도 지난 기록이 유지되는가?","실제 오늘 날짜가 정확하게 구분되는가?","미래 날짜를 기록할 수 있는지 규칙이 명확한가?","날짜 버튼을 키보드와 모바일 터치로 조작할 수 있는가?"]},
{title:"사용 · 돌아오기가 쉬웠는지 보기",paragraphs:["실제 사용 결과는 아직 없습니다. 사용하게 되면 쉬었던 날의 길이, 다시 열었을 때 느낀 부담, 체크가 실천을 돕는지 등을 짧게 기록합니다.","기록표에 표시가 늘어나는 것만으로 습관이 좋아졌다고 결론 내리지 않습니다. 기록하는 일이 오히려 부담이 되는지도 살펴봅니다."]},
{title:"개선 · 회복을 돕는 만큼만",paragraphs:["돌아온 날에 짧은 메모가 도움이 되는지, 달력보다 목록이 읽기 쉬운지 사용 후 판단합니다. 그래프나 점수는 그 정보가 실제로 필요한 경우에만 추가합니다.","결국 기존 수첩이 더 편하다면 이 도구를 중단해도 됩니다. 그 이유를 구체적으로 남기는 것도 실험의 결과입니다."]},
{title:"현재 상태 · 제작 전 기획 예시",paragraphs:["아직 만들어지지 않은 도구이며, 습관 개선 효과를 검증하지 않았습니다. 화면의 체크 표시는 예시입니다.","먼저 실제로 다시 시작하고 싶은 습관 하나를 정하고, 무엇을 ‘한 날’로 기록할지 명확하게 적어보세요."]}
]},
en:{title:"A habit tracker that welcomes you back",excerpt:"Pay attention to the day you return, not the streak. An experiment in recording habits without letting a missed day become a stopping point.",category:"Notes & reflection",sections:[
{title:"Problem · Does one missed day mean starting over?",paragraphs:["A streak can be motivating, but it can also make a missed day feel heavy. Imagine a tracker designed for someone who stops recording after a break.","This is a hypothetical planning example, not a build or usage report. Its effects need to be checked through actual use."]},
{title:"Requirements · Quietly record the days you did it",paragraphs:["Choose one habit and mark the days you practiced it on a calendar. No streak ranking or failure alerts. Returning after a break should use the same simple action.","Allow mistakes to be undone. Reading one month’s records on one screen is enough for the first version."]},
{title:"Build · Explain what the record should mean",paragraphs:["Describe the approach to recording, rather than just asking for a habit app. This is an untested sample prompt."],prompt:"Build a personal habit tracker that makes returning easy.\n\nTrack one habit. Tapping a day in this month’s calendar marks it; tapping again undoes the mark. No streak count, rankings, or failure messages. A missed day must not prevent returning.\n\nKeep records in the same browser after refresh. First explain how past months and future dates will be handled."},
{title:"Verify · Check dates and undo behavior",paragraphs:["Date-based tools can behave unexpectedly at month boundaries or in different time zones. Compare the displayed calendar with the dates actually stored."],checklist:["Does tapping the same day twice undo its mark?","Are past records retained when the month changes?","Is the current local date identified correctly?","Is the rule for marking future dates clear?","Can date controls be used with a keyboard and a touch screen?"]},
{title:"Use · Observe whether returning feels easier",paragraphs:["There are no usage results yet. If built, record the length of breaks, how it feels to return, and whether checking a box supports the habit.","More marks do not automatically mean a better habit. Notice whether recording itself becomes a burden."]},
{title:"Improve · Add only what helps you return",paragraphs:["Decide through use whether a brief note helps, or whether a list is easier to read than a calendar. Add scores or charts only when their information is useful.","If a paper notebook works better, stopping the tool is a valid choice. A specific explanation is also an experiment’s result."]},
{title:"Current status · A planning example",paragraphs:["This tool has not been built. No benefit to habit formation has been verified, and the calendar marks are examples.","Choose one habit you actually want to return to and clearly define what qualifies as a practiced day."]}
]}},
{slug:"five-minute-start",programId:"five-minute-start",number:"03",kind:"example",status:"planned",completed:false,preview:"timer",updatedAt:"2026-10-02",tools:[],
ko:{title:"큰 계획 대신, 시작하기 위한 5분 타이머",excerpt:"집중 시간을 늘리기 전에 시작의 문턱부터 낮춰봅니다. 버튼 하나로 시작하는 작은 타이머를 어떻게 확인할까요?",category:"집중과 시작",sections:[
{title:"불편 · 할 일은 아는데 시작하기 어렵다",paragraphs:["할 일을 모르는 것이 아니라, 오래 해야 한다는 생각 때문에 시작을 미루는 상황을 가정해 봅니다. 딱 5분만 해보는 타이머가 시작의 부담을 줄일 수 있을까요?", "이 글은 제작 전 기획 예시입니다. 시작이 쉬워졌다는 실제 경험이나 측정 결과는 아직 없습니다."]},
{title:"요구 · 한 번 눌러 시작하기",paragraphs:["첫 화면에는 5분과 시작 버튼이 있습니다. 시작하면 남은 시간을 보여주고, 잠시 멈추거나 처음으로 되돌릴 수 있습니다. 시간이 끝나면 화면으로 알려줍니다.","작업 분류, 통계, 긴 집중 세션은 첫 버전에서 제외합니다. 타이머가 같은 속도로 흐르고 버튼이 예측 가능하게 동작하는 것이 먼저입니다."]},
{title:"제작 · 정상 동작과 예외를 함께 요청하기",paragraphs:["간단한 타이머도 중복 실행이나 화면 전환을 다뤄야 합니다. 아래는 아직 실행하지 않은 요청문 예시입니다."],prompt:"작업을 시작하기 위한 5분 타이머를 만들어 주세요.\n\n시작, 일시정지, 초기화 기능만 필요합니다. 시작 버튼을 여러 번 눌러도 카운트다운이 중복 실행되면 안 됩니다. 다른 탭에 갔다 돌아와도 실제 경과 시간에 맞게 표시해 주세요.\n\n0초에서 멈추고 완료 상태를 화면과 보조 기술로 알려주세요. 자동 소리 재생과 통계 기능은 넣지 않습니다. 새로고침하면 초기 상태가 되는 것을 안내해 주세요."},
{title:"확인 · 한 번 더 누르고, 다른 탭에 가보기",paragraphs:["‘시작 버튼을 두 번 눌렀더니 빨라졌다’는 실제 보고가 아닙니다. 그런 오류가 생길 수 있는지 확인할 테스트 상황입니다. 남은 시간을 눈으로만 보지 말고 실제 경과 시간과 비교해야 합니다."],checklist:["시작 버튼을 빠르게 두 번 눌러도 속도가 같은가?","일시정지 후 다시 시작하면 남은 시간이 이어지는가?","다른 탭에서 돌아왔을 때 실제 경과 시간과 맞는가?","0초 아래로 내려가지 않고 종료되는가?","실행 중 초기화하면 이전 카운트다운이 확실히 멈추는가?"]},
{title:"사용 · 5분 뒤에 무엇이 일어나는가",paragraphs:["사용 결과는 아직 없습니다. 실제로 쓰게 되면 어떤 일을 시작할 때 켰는지, 5분 뒤 계속했는지 멈췄는지, 타이머가 방해가 되지는 않았는지를 적어둘 계획입니다.","계속하지 않았어도 실패로 분류하지 않습니다. 도구의 목적은 긴 집중을 강요하는 것이 아니라, 내가 원할 때 시작을 돕는 것입니다."]},
{title:"개선 · 더 길게보다 더 쉽게",paragraphs:["5분이 맞는 길이인지, 종료 안내가 필요한지, 시간을 보는 일이 오히려 부담이 되는지는 써본 뒤 판단합니다. 시간을 고르는 설정도 필요가 확인된 뒤에 추가합니다.","문제가 생기면 누른 버튼의 순서, 다른 탭에 있었는지, 사용한 기기와 브라우저를 남깁니다. 재현 가능한 상황이 있어야 수정 결과도 확인할 수 있습니다."]},
{title:"현재 상태 · 제작 전 기획 예시",paragraphs:["타이머는 아직 제작하지 않았고, 화면에 보이는 05:00은 구성 예시입니다. 실행 가능한 공개 프로그램이 아닙니다.","먼저 지금 시작을 미루고 있는 일 하나를 고르고, 5분 안에 할 수 있는 가장 작은 행동을 적어보세요."]}
]},
en:{title:"A five-minute timer to make starting smaller",excerpt:"Before extending your focus, lower the threshold for starting. How would you verify a tiny timer that begins with one button?",category:"Focus & getting started",sections:[
{title:"Problem · Knowing what to do, but not starting",paragraphs:["Imagine putting off a task because it feels like a long commitment, even though you know what to do. Could a five-minute timer make starting feel smaller?", "This is a planning example. There is no firsthand experience or measured improvement yet."]},
{title:"Requirements · Start with one press",paragraphs:["Show five minutes and a start button. Once running, show the remaining time and allow pausing or resetting. Indicate completion on screen.","Leave task categories, statistics, and long focus sessions out of the first version. Accurate timing and predictable controls come first."]},
{title:"Build · Ask for normal and exceptional behavior",paragraphs:["Even a simple timer needs to handle repeated clicks and tab switching. This sample prompt has not been run."],prompt:"Build a five-minute timer for getting started on a task.\n\nInclude only start, pause, and reset. Repeated clicks on start must never create duplicate countdowns. When returning from another tab, show the correct remaining time based on elapsed time.\n\nStop at zero and announce completion visually and to assistive technology. No automatic audio or statistics. Explain that refreshing returns it to its initial state."},
{title:"Verify · Click twice, then switch tabs",paragraphs:["A timer speeding up after a double-click is a test scenario, not an observed bug here. Compare the remaining time with actual elapsed time rather than only watching the display."],checklist:["Does rapid double-clicking leave the countdown speed unchanged?","Does resuming continue from the paused time?","Does returning from another tab show the correct remaining time?","Does the timer stop at zero without becoming negative?","Does resetting stop the previous countdown completely?"]},
{title:"Use · What happens after five minutes?",paragraphs:["There are no usage results yet. If built, note what task it helped begin, whether you continued after five minutes, and whether the timer was distracting.","Stopping after five minutes does not need to count as failure. The tool’s purpose is to support starting when you want to."]},
{title:"Improve · Make it easier before making it longer",paragraphs:["Use the tool to decide whether five minutes is appropriate, whether an ending notice helps, and whether watching time feels burdensome. Add duration settings only after a real need appears.","For a bug, record the sequence of button presses, whether the tab was hidden, and the device and browser. Reproducible circumstances make fixes verifiable."]},
{title:"Current status · A planning example",paragraphs:["The timer has not been built. The 05:00 display is a conceptual layout, not a runnable public program.","Choose one task you are delaying and write down the smallest action you could take in five minutes."]}
]}}
];
export const getPost=(slug:string)=>posts.find(post=>post.slug===slug);
export const copyFor=(post:Post,locale:Locale)=>post[locale];
export const completedCount=()=>new Set(posts.filter(p=>p.kind==="experience" && p.completed).map(p=>p.programId)).size;

export const statusLabel=(status:Post["status"],locale:Locale)=>({planned:text(locale,"제작 전","Not built yet"),using:text(locale,"계속 사용","In use"),improving:text(locale,"개선 예정","Improving"),stopped:text(locale,"사용 중단","Stopped")})[status];
export const recentPosts=()=>[...posts].sort((a,b)=>(a.kind==="experience" ? 0 : 1)-(b.kind==="experience" ? 0 : 1)||b.updatedAt.localeCompare(a.updatedAt)).slice(0,3);
